import pyjokes

# Get a random joke
joke = pyjokes.get_joke()
print(joke) 


""" 
 THIS IS THE THANK UHH MESSAGE IN THE MULTI LINE COMMENT, I CAN USE THIS TO WRITE ANYTHING I WANT, AND IT WONT AFFECT THE CODE, I CAN ALSO USE THIS TO COMMENT OUT A LARGE BLOCK OF CODE WITHOUT HAVING TO PUT # IN FRONT OF EACH LINE.

"""
